(() => {
  const verses = document.querySelector('#verses');
  const heading = document.querySelector('.chapter-heading');
  const toolbar = document.querySelector('.toolbar');
  if (!verses) return;

  const STORE_KEY = 'bible-reader-verse-marks-v1';
  const CHAPTER_KEY = 'bible-reader-chapter-bookmarks-v1';
  const LABELS = {
    ko:{copy:'복사',highlight:'하이라이트',removeHighlight:'강조 해제',saveVerse:'구절 저장',removeVerse:'구절 저장 해제',note:'메모',noteTitle:'구절 메모',save:'저장',removeNote:'메모 삭제',cancel:'취소',chapterBookmark:'장 북마크',removeChapterBookmark:'장 북마크 해제',notebook:'메모장',notebookTitle:'나의 기록',notesTab:'메모',savedTab:'저장한 성구',highlightTab:'하이라이트',emptyNotes:'저장된 메모가 없습니다.',emptySaved:'저장한 성구가 없습니다.',emptyHighlights:'하이라이트한 성구가 없습니다.',go:'구절로 이동',close:'닫기'},
    en:{copy:'Copy',highlight:'Highlight',removeHighlight:'Remove highlight',saveVerse:'Save verse',removeVerse:'Remove saved verse',note:'Note',noteTitle:'Verse note',save:'Save',removeNote:'Delete note',cancel:'Cancel',chapterBookmark:'Bookmark chapter',removeChapterBookmark:'Remove chapter bookmark',notebook:'Notes',notebookTitle:'My records',notesTab:'Notes',savedTab:'Saved verses',highlightTab:'Highlights',emptyNotes:'No saved notes.',emptySaved:'No saved verses.',emptyHighlights:'No highlighted verses.',go:'Go to verse',close:'Close'},
    fr:{copy:'Copier',highlight:'Surligner',removeHighlight:'Retirer le surlignage',saveVerse:'Enregistrer',removeVerse:'Retirer',note:'Note',noteTitle:'Note du verset',save:'Enregistrer',removeNote:'Supprimer',cancel:'Annuler',chapterBookmark:'Ajouter ce chapitre',removeChapterBookmark:'Retirer ce chapitre',notebook:'Notes',notebookTitle:'Mes notes',notesTab:'Notes',savedTab:'Versets enregistrés',highlightTab:'Surlignés',emptyNotes:'Aucune note.',emptySaved:'Aucun verset enregistré.',emptyHighlights:'Aucun verset surligné.',go:'Aller au verset',close:'Fermer'},
    de:{copy:'Kopieren',highlight:'Markieren',removeHighlight:'Markierung entfernen',saveVerse:'Vers speichern',removeVerse:'Vers entfernen',note:'Notiz',noteTitle:'Versnotiz',save:'Speichern',removeNote:'Notiz löschen',cancel:'Abbrechen',chapterBookmark:'Kapitel merken',removeChapterBookmark:'Kapitel entfernen',notebook:'Notizen',notebookTitle:'Meine Einträge',notesTab:'Notizen',savedTab:'Gespeicherte Verse',highlightTab:'Markiert',emptyNotes:'Keine Notizen.',emptySaved:'Keine gespeicherten Verse.',emptyHighlights:'Keine markierten Verse.',go:'Zum Vers',close:'Schließen'},
    zh:{copy:'复制',highlight:'高亮',removeHighlight:'取消高亮',saveVerse:'保存经文',removeVerse:'取消保存',note:'笔记',noteTitle:'经文笔记',save:'保存',removeNote:'删除笔记',cancel:'取消',chapterBookmark:'收藏本章',removeChapterBookmark:'取消收藏本章',notebook:'笔记本',notebookTitle:'我的记录',notesTab:'笔记',savedTab:'已保存经文',highlightTab:'高亮',emptyNotes:'暂无笔记。',emptySaved:'暂无保存的经文。',emptyHighlights:'暂无高亮经文。',go:'前往经文',close:'关闭'},
    ru:{copy:'Копировать',highlight:'Выделить',removeHighlight:'Убрать выделение',saveVerse:'Сохранить стих',removeVerse:'Удалить стих',note:'Заметка',noteTitle:'Заметка к стиху',save:'Сохранить',removeNote:'Удалить заметку',cancel:'Отмена',chapterBookmark:'Закладка главы',removeChapterBookmark:'Убрать закладку',notebook:'Заметки',notebookTitle:'Мои записи',notesTab:'Заметки',savedTab:'Сохранённые стихи',highlightTab:'Выделенные',emptyNotes:'Нет заметок.',emptySaved:'Нет сохранённых стихов.',emptyHighlights:'Нет выделенных стихов.',go:'К стиху',close:'Закрыть'},
    la:{copy:'Copia',highlight:'Nota',removeHighlight:'Notam remove',saveVerse:'Serva versum',removeVerse:'Remove versum',note:'Commentarium',noteTitle:'Commentarium versus',save:'Serva',removeNote:'Remove',cancel:'Claude',chapterBookmark:'Serva caput',removeChapterBookmark:'Remove caput',notebook:'Commentaria',notebookTitle:'Mea',notesTab:'Commentaria',savedTab:'Versus servati',highlightTab:'Notati',emptyNotes:'Nulla commentaria.',emptySaved:'Nulli versus servati.',emptyHighlights:'Nulli versus notati.',go:'Ad versum',close:'Claude'}
  };

  let marks = loadJson(STORE_KEY);
  let chapterBookmarks = loadJson(CHAPTER_KEY);
  let activeToolbar = null;
  let noteEditor = null;
  let notebookPanel = null;
  let notebookTab = 'notes';

  function lang() { if (window.BibleI18n?.lang) return window.BibleI18n.lang(); const tr = window.TRANSLATIONS?.[document.querySelector('#translationSelect')?.value]; return tr?.lang || (tr?.id === 'krv1961' ? 'ko' : 'en'); }
  function labels(){ return LABELS[lang()] || LABELS.en; }
  function loadJson(key){ try { return JSON.parse(localStorage.getItem(key)) || {}; } catch (_) { return {}; } }
  function saveMarks(){ localStorage.setItem(STORE_KEY, JSON.stringify(marks)); }
  function saveChapterBookmarks(){ localStorage.setItem(CHAPTER_KEY, JSON.stringify(chapterBookmarks)); }
  function translation(){ return document.querySelector('#translationSelect')?.value || 'krv1961'; }
  function bookIndex(){ return typeof state !== 'undefined' ? state.bookIndex : 0; }
  function chapterNumber(){ return typeof state !== 'undefined' ? state.chapter : 1; }
  function currentKey(verse){ return `${translation()}:${bookIndex()}:${chapterNumber()}:${verse}`; }
  function currentChapterKey(){ return `${translation()}:${bookIndex()}:${chapterNumber()}`; }
  function currentBookName(){ return window.BibleI18n?.bookName ? window.BibleI18n.bookName(bookIndex()) : BOOKS[bookIndex()].ko; }
  function currentReference(verse){ return `${currentBookName()} ${chapterNumber()}:${verse}`; }
  function markFor(key){ return marks[key] || {highlight:false,bookmark:false,note:''}; }
  function bookNameFor(index){ return window.BibleI18n?.bookName ? window.BibleI18n.bookName(index) : (BOOKS[index]?.ko || ''); }

  function applyMarks(){
    verses.querySelectorAll('.verse').forEach(row => { const key=currentKey(row.dataset.verse), mark=markFor(key); row.classList.toggle('user-highlight',!!mark.highlight); row.classList.toggle('user-bookmarked',!!mark.bookmark); row.classList.toggle('user-noted',!!mark.note?.trim()); ensureTrigger(row); });
    ensureChapterBookmark(); ensureNotebookButton(); updateChapterBookmark(); if(notebookPanel) renderNotebook();
  }

  function ensureTrigger(row){ if(row.querySelector('.verse-actions-trigger'))return; const button=document.createElement('button'); button.type='button'; button.className='verse-actions-trigger'; button.textContent='⋯'; button.setAttribute('aria-label','Verse actions'); button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();openToolbar(row,button);}); row.append(button); }
  function ensureChapterBookmark(){ if(!heading||heading.querySelector('.chapter-bookmark-button'))return; const button=document.createElement('button'); button.type='button'; button.className='chapter-bookmark-button'; button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const key=currentChapterKey();if(chapterBookmarks[key])delete chapterBookmarks[key];else chapterBookmarks[key]={translation:translation(),bookIndex:bookIndex(),chapter:chapterNumber(),label:`${currentBookName()} ${chapterNumber()}장`,savedAt:Date.now()};saveChapterBookmarks();updateChapterBookmark();}); heading.querySelector('h1')?.insertAdjacentElement('afterend',button); }
  function ensureNotebookButton(){ if(!toolbar||toolbar.querySelector('.notebook-button'))return; const button=document.createElement('button');button.type='button';button.className='text-button notebook-button';button.textContent=labels().notebook;button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();notebookPanel?closeNotebook():openNotebook();});toolbar.append(button); }
  function updateChapterBookmark(){ const button=heading?.querySelector('.chapter-bookmark-button');if(!button)return;const saved=!!chapterBookmarks[currentChapterKey()],l=labels();button.textContent=saved?'★':'☆';button.classList.toggle('active',saved);button.title=saved?l.removeChapterBookmark:l.chapterBookmark;button.setAttribute('aria-label',saved?l.removeChapterBookmark:l.chapterBookmark);button.setAttribute('aria-pressed',saved?'true':'false'); }
  function closeToolbar(){activeToolbar?.remove();activeToolbar=null;} function closeNoteEditor(){noteEditor?.remove();noteEditor=null;} function closeNotebook(){notebookPanel?.remove();notebookPanel=null;document.body.classList.remove('notebook-open');}
  function actionButton(text,handler){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();handler();});return b;}
  function openNoteEditor(row,key){closeToolbar();closeNoteEditor();const l=labels(),mark=markFor(key),editor=document.createElement('div');editor.className='verse-note-editor';const title=document.createElement('strong');title.textContent=`${l.noteTitle} · ${currentReference(Number(row.dataset.verse))}`;const textarea=document.createElement('textarea');textarea.value=mark.note||'';textarea.placeholder=l.note;const actions=document.createElement('div');actions.className='verse-note-actions';const save=actionButton(l.save,()=>{const next=markFor(key);next.note=textarea.value.trim();marks[key]=next;saveMarks();applyMarks();closeNoteEditor();});const remove=actionButton(l.removeNote,()=>{const next=markFor(key);next.note='';marks[key]=next;saveMarks();applyMarks();closeNoteEditor();});actions.append(save,remove,actionButton(l.cancel,closeNoteEditor));editor.append(title,textarea,actions);document.body.append(editor);noteEditor=editor;requestAnimationFrame(()=>textarea.focus());}
  function allEntries(){return Object.entries(marks).map(([key,mark])=>{const[tr,book,chapter,verse]=key.split(':');return{key,mark,tr,bookIndex:Number(book),chapter:Number(chapter),verse:Number(verse)}}).sort((a,b)=>a.bookIndex-b.bookIndex||a.chapter-b.chapter||a.verse-b.verse);}
  function noteEntries(){return allEntries().filter(item=>item.mark?.note?.trim());} function savedEntries(){return allEntries().filter(item=>item.mark?.bookmark);} function highlightedEntries(){return allEntries().filter(item=>item.mark?.highlight);}
  async function goToEntry(item,editNote=false){activeTranslationId=TRANSLATIONS[item.tr]?item.tr:activeTranslationId;if(translationSelect)translationSelect.value=activeTranslationId;state.bookIndex=item.bookIndex;state.chapter=item.chapter;await loadCurrent({scrollTop:false});closeNotebook();requestAnimationFrame(()=>{const row=verses.querySelector(`[data-verse="${item.verse}"]`);if(!row)return;if(editNote)openNoteEditor(row,item.key);else{row.classList.add('searched');row.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>row.classList.remove('searched'),1800);}});}
  async function fillEntryText(item,target){if(item.mark.savedText){target.textContent=item.mark.savedText;return;}try{const data=await fetchBook(BOOKS[item.bookIndex],item.tr);const ch=data.chapters.find(c=>Number(c.chapter)===item.chapter);const verse=ch?.verses.find(v=>Number(v.verse)===item.verse);if(verse?.text)target.textContent=verse.text;}catch(_){}}
  function renderNotebook(){if(!notebookPanel)return;const l=labels(),list=notebookPanel.querySelector('.notebook-list');notebookPanel.querySelector('.notebook-title').textContent=l.notebookTitle;notebookPanel.querySelector('.notebook-close').textContent=l.close;const notesTab=notebookPanel.querySelector('[data-tab="notes"]'),savedTab=notebookPanel.querySelector('[data-tab="saved"]'),highlightTab=notebookPanel.querySelector('[data-tab="highlights"]');notesTab.textContent=l.notesTab;savedTab.textContent=l.savedTab;highlightTab.textContent=l.highlightTab;[notesTab,savedTab,highlightTab].forEach(tab=>{const active=tab.dataset.tab===notebookTab;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});list.innerHTML='';const entries=notebookTab==='notes'?noteEntries():notebookTab==='saved'?savedEntries():highlightedEntries(),emptyText=notebookTab==='notes'?l.emptyNotes:notebookTab==='saved'?l.emptySaved:l.emptyHighlights;if(!entries.length){const empty=document.createElement('p');empty.className='notebook-empty';empty.textContent=emptyText;list.append(empty);return;}entries.forEach(item=>{const card=document.createElement('article');card.className=`notebook-item ${notebookTab==='highlights'?'highlight-item':''}`;const ref=document.createElement('strong');ref.textContent=`${bookNameFor(item.bookIndex)} ${item.chapter}:${item.verse}`;const body=document.createElement('p');if(notebookTab==='notes')body.textContent=item.mark.note;else{body.className='saved-verse-text';body.textContent=item.mark.savedText||'본문을 불러오는 중…';fillEntryText(item,body);}const actions=document.createElement('div');actions.className='notebook-item-actions';actions.append(actionButton(l.go,()=>goToEntry(item,false)));if(notebookTab==='notes')actions.append(actionButton(l.note,()=>goToEntry(item,true)));card.append(ref,body,actions);list.append(card);});}
  function openNotebook(){closeToolbar();closeNoteEditor();closeNotebook();const panel=document.createElement('aside');panel.className='notebook-panel';panel.setAttribute('aria-label',labels().notebookTitle);const head=document.createElement('div');head.className='notebook-head';const title=document.createElement('strong');title.className='notebook-title';const close=document.createElement('button');close.type='button';close.className='notebook-close';close.addEventListener('click',closeNotebook);const tabs=document.createElement('div');tabs.className='notebook-tabs';tabs.setAttribute('role','tablist');['notes','saved','highlights'].forEach(tab=>{const b=document.createElement('button');b.type='button';b.dataset.tab=tab;b.setAttribute('role','tab');b.addEventListener('click',()=>{notebookTab=tab;renderNotebook();});tabs.append(b);});const list=document.createElement('div');list.className='notebook-list';head.append(title,close);panel.append(head,tabs,list);document.body.append(panel);notebookPanel=panel;document.body.classList.add('notebook-open');renderNotebook();}
  function openToolbar(row,anchor){closeToolbar();closeNoteEditor();const verse=Number(row.dataset.verse),key=currentKey(verse),mark=markFor(key),l=labels(),bar=document.createElement('div');bar.className='verse-action-popover';const rect=anchor.getBoundingClientRect();bar.style.top=`${window.scrollY+rect.bottom+6}px`;bar.style.left=`${Math.max(12,Math.min(window.scrollX+rect.left-220,window.scrollX+window.innerWidth-420))}px`;bar.append(actionButton(l.copy,async()=>{const text=row.querySelector('.verse-text')?.textContent?.trim()||'';try{await navigator.clipboard.writeText(`${currentReference(verse)}\n${text}`);}catch(_){}closeToolbar();}),actionButton(mark.highlight?l.removeHighlight:l.highlight,()=>{const next=markFor(key);next.highlight=!next.highlight;if(next.highlight)next.savedText=row.querySelector('.verse-text')?.textContent?.trim()||next.savedText||'';marks[key]=next;saveMarks();applyMarks();closeToolbar();}),actionButton(l.note,()=>openNoteEditor(row,key)),actionButton(mark.bookmark?l.removeVerse:l.saveVerse,()=>{const next=markFor(key);next.bookmark=!next.bookmark;if(next.bookmark)next.savedText=row.querySelector('.verse-text')?.textContent?.trim()||next.savedText||'';marks[key]=next;saveMarks();applyMarks();closeToolbar();}));document.body.append(bar);activeToolbar=bar;}
  document.addEventListener('click',e=>{if(activeToolbar&&!activeToolbar.contains(e.target))closeToolbar();if(noteEditor&&!noteEditor.contains(e.target))closeNoteEditor();});
  window.addEventListener('scroll',closeToolbar,{passive:true});window.addEventListener('resize',closeToolbar);
  ['translationSelect','bookSelect','chapterSelect'].forEach(id=>document.querySelector(`#${id}`)?.addEventListener('change',()=>setTimeout(applyMarks,350)));
  window.addEventListener('bible-reader-records-changed',()=>{marks=loadJson(STORE_KEY);chapterBookmarks=loadJson(CHAPTER_KEY);applyMarks();});
  const observer=new MutationObserver(()=>requestAnimationFrame(applyMarks));observer.observe(verses,{childList:true});applyMarks();
})();